all: copy

copy: 
	mkdir -p $(HOME)/cmpt433/public/myApps/cmpt433Proj
	cp -r $(HOME)/cmpt433/work/cmpt433finalproject/webserver_src $(HOME)/cmpt433/public/myApps/cmpt433Proj

clean:
	rm -rf $(HOME)/cmpt433/public/myApps/cmpt433Proj/webserver_src_copy